### ISSUE TITLE
[brd_pos_receipt] Tidak berhasil load pos

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/brd#21]
Ketika open session atau resume session, layar berhenti ketika pos sufah berhasil meload semua data. Namun tampilan pos tidak muncul.

Coba cari apakah ada pengaruhnya jika modul pos berbayar diinstall.

**Comment by mikevhe18** [comment]
Analisa - 1 : 
1. Module brd_pos_receipt diinstal
2. Module opensynergy_app_store diinstall

Analisa - 2 : 
1. Module opensynergy_app_store diinstall
2. Module brd_pos_receipt diinstall

Hasil : 
1. Analisa - 1 gak ada masalah, POS bisa dibuka
2. Analisa - 2 terjadi masalah, POS tidak loading

**Comment by mikevhe18** [comment]
Mas, untuk masalah ini penyebabnya ternyata karena masalah data yang gak diisi..

Data yg harus diisi itu field owner di POS configuration, sama alamatnya..

Validasi fiedlnya lagi dicari dulu caranya, karena belum nemu di JSnya..
Jadi sementara, problem ini disolvenya dengan data harus diisi

**Comment by andhit-r** [comment]
@mikevhe18 data apa saja yang harus diisi

**Comment by mikevhe18** [comment]
@andhit-r Data yang perlu diisi adalah data Owner pada Stock Location. Kemudian untuk partnernya data country_id dan state_id harus diisi.
